version: 2.1

executors:
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    working_directory: ~/workspace

jobs:
  build:
    executor: jdk11
    steps:
      - checkout
      - run: mvn

workflows:
  version: 2
  continuous_integration:
    jobs:
      - build
